name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm install
      continue-on-error: true  # Continue even if there's an error, to capture more logs

    - name: Run backend tests
      working-directory: ./backend
      run: |
        npm test
      continue-on-error: true  # Continue even if there's an error, to capture more logs

    - name: Print logs
      if: failure()
      run: dmesg # Capture system logs for debugging

  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
      continue-on-error: true  # Continue even if there's an error, to capture more logs

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        npm test
      continue-on-error: true  # Continue even if there's an error, to capture more logs

    - name: Print logs
      if: failure()
      run: dmesg # Capture system logs for debugging
      
    - name: Set environment variables
      run: |
        echo "NODE_ENV=production" >> $GITHUB_ENV
